---
- src: https://github.com/feffi/ansible-macos-standby.git
  name: feffi.macos-standby
- src: geerlingguy.homebrew
- src: https://github.com/ccdc-opensource/ansible-role-ccdc-package-manager-configuration.git
  scm: git
  name: ccdc.package_manager_configuration
