---
roles:
- src: https://github.com/feffi/ansible-macos-standby.git
  name: feffi.macos-standby
- src: https://github.com/feffi/ansible-macos-defaults.git
  name: feffi.macos-defaults
- src: ccdc.package_manager_configuration

collections:
- name: geerlingguy.mac
