---
- name: Set up package managers for required tools
  ansible.builtin.include_role:
    name: ccdc.package_manager_configuration

- name: Install desktop environment
  ansible.builtin.package:
    name: "{{ package }}"
  loop: "{{ desktop_packages }}"
  loop_control:
    loop_var: package
  become: true
  
- name: Run common Linux setup
  ansible.builtin.include_tasks: Linux.yml
