---
- name: Never Sleep Mode
  ansible.builtin.command: "{{ item }}"
  with_items:
    - pmset -a standbydelay 0
    - pmset -a displaysleep 0
    - pmset -a disablesleep 1
    - pmset -a disksleep 0
    - pmset -a hibernatemode 0
    - pmset disablesleep 1
    #  Not sure the stuff below works
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false
  become: true

- name: Install Homebrew + kcpassword
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_taps:
      - name: xfreebird/utils
    homebrew_installed_packages:
      - xfreebird/utils/kcpassword

# - name: Add kcpassword utility for autologin
#   community.general.homebrew:
#     name: kcpassword
#     state: present
#   become: true

- name: Set autoLoginUser for current user
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: autoLoginUser
    type: string
    value: "{{ ansible_env.USER }}"
    state: present
  become: true

- name: Set the autologon password for current user # noqa: no-changed-when
  ansible.builtin.command:
    cmd: kcpassword "{{ ansible_env.USER }}"
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  become: true

- name: Set Europe/London time zone
  community.general.timezone:
    name: "Europe/London"
  register: timezone_result
  become: true

- name: Debug timezone
  debug:
    var: timezone_result

- name: Wait for 5 seconds
  wait_for:
    timeout: 5
