---
- name: Disable Sleep
  ansible.builtin.command: "{{ item }}"
  with_items:
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false
  become: true

- name: Additional cleanups for never sleep mode
  ansible.builtin.include_role:
    name: feffi.macos-standby
  vars:
    standby_delay: false  # noqa: var-naming[no-role-prefix]
    hibernate_mode: 0  # noqa: var-naming[no-role-prefix]
    remove_sleepimage: true  # noqa: var-naming[no-role-prefix]

- name: Ensure homebrew is installed
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew

- name: Add xfreebird/utils tap for kcpassword
  community.general.homebrew_tap:
    name: xfreebird/utils
    state: present

- name: Add kcpassword utility for autologin
  community.general.homebrew:
    name: kcpassword
    state: present

- name: Set autoLoginUser
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: autoLoginUser
    type: string
    value: vagrant
    state: present
  become: true

- name: Set the autologon password # noqa: no-changed-when
  ansible.builtin.command: /usr/local/bin/kcpassword "vagrant"
  become: true

- name: Set Europe/London time zone
  community.general.timezone:
    name: "Europe/London"
  become: true
