---
- name: Never Sleep Mode
  ansible.builtin.command: "{{ item }}"
  with_items:
    - pmset -a standbydelay 0
    - pmset -a displaysleep 0
    - pmset -a disablesleep 1
    - pmset -a disksleep 0
    - pmset -a hibernatemode 0
    - pmset disablesleep 1
    #  Not sure the stuff below works
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false
  become: true

- name: Install Homebrew + kcpassword
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_taps:
      - name: xfreebird/utils
    homebrew_installed_packages:
      - xfreebird/utils/kcpassword
  when: not cpp_buildmachine

# - name: Add kcpassword utility for autologin
#   community.general.homebrew:
#     name: kcpassword
#     state: present
#   become: true

- name: Check if vagrant user exists
  ansible.builtin.command:
    cmd: id -u vagrant
  register: vagrant_user
  ignore_errors: true

- name: Set autoLoginUser for vagrant
  when: vagrant_user.rc == 0
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: autoLoginUser
    type: string
    value: vagrant
    state: present
  become: true

- name: Set the autologon password for vagrant # noqa: no-changed-when
  when: vagrant_user.rc == 0
  ansible.builtin.command:
    cmd: kcpassword vagrant
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  become: true

- name: Check if ec2-user user exists
  ansible.builtin.command:
    cmd: id -u ec2-user
  register: ec2_user
  ignore_errors: true

- name: Set autoLoginUser for ec2-user
  when: ec2_user.rc == 0
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: autoLoginUser
    type: string
    value: ec2-user
    state: present
  become: true

- name: Set the autologon password for ec2-user # noqa: no-changed-when
  when: ec2_user.rc == 0
  ansible.builtin.command:
    cmd: kcpassword ec2-user
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  become: true

- name: Set Europe/London time zone
  community.general.timezone:
    name: "Europe/London"
  become: true
