---
- name: Install desktop environment
  apt:
    name:
      - ubuntu-desktop
      - firefox
      # psutil is required by the dconf module
      - python3-psutil
      - python-psutil
    update_cache: yes
  become: true

- include_tasks: Linux.yml
