---
- name: Install desktop environment
  ansible.builtin.apt:
    name:
      - ubuntu-desktop
      - firefox
      # psutil is required by the dconf module
      - python3-psutil
      # - python-psutil
    state: present
    update_cache: true
  become: true

- ansible.builtin.include_tasks: Linux.yml
