---
- name: Install desktop environment
  ansible.builtin.apt:
    name:
      - ubuntu-desktop-minimal
      - firefox
      # psutil is required by ansible's dconf module
      - python3-psutil
    state: present
    update_cache: true
  become: true

- name: Run common Linux setup
  ansible.builtin.include_tasks: Linux.yml
