---
- name: Install desktop environment
  apt:
    name:
      - ubuntu-desktop
      - firefox
      # psutil is required by the dconf module
      - python3-psutil
      - python-psutil
    update_cache: yes
  become: yes

- name: Link /etc/gdm to /etc/gdm3
  file:
    src: /etc/gdm3
    dest: /etc/gdm
    state: link
  become: yes

- include_tasks: Linux.yml
