---
- name: Install CSDS to {{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ansible_os_family}}-{{ ansible_distribution }}.yml"
        - "{{ansible_os_family}}.yml"
      skip: yes
