---
- name: Set OS-specific variables for {{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "vars/{{ansible_os_family}}-{{ ansible_distribution_major_version}}.yml"
        - "vars/{{ansible_os_family}}-{{ ansible_distribution }}.yml"
        - "vars/{{ansible_os_family}}.yml"
        - "vars/{{ansible_system}}.yml"
      skip: true
  tags: vars

- name: Set up desktop environment on {{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ansible_os_family}}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ansible_os_family}}-{{ ansible_distribution }}.yml"
        - "{{ansible_os_family}}.yml"
      skip: yes
