---
- name: Set up package managers for required tools
  include_role:
    name: ccdc.package_manager_configuration

- name: Install desktop environment
  package:
    name: "{{ package }}"
  loop: "{{ desktop_packages }}"
  loop_control:
    loop_var: package
  become: true

- include_tasks: Linux.yml
