---
- name: Set up package managers for required tools
  include_role:
    name: ccdc-package-manager-configuration

- name: Install desktop environment
  yum:
    name:
      - "@^gnome-desktop-environment"
      - firefox
      # This is required for the dconf module to disable screen locking
      - python2-psutil
  become: yes

- name: Set vagrant user for autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: vagrant
    mode: '0644'
  become: yes

- name: Enable autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: 'True'
    mode: '0644'
  become: yes

- name: Set GUI boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  become: yes

- name: Enable and start GDM
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: yes

- name: Disable idle screen lock
  dconf:
    key: "{{ option.key }}"
    value: "{{ option.value }}"
  loop:
    - { 'key': '/org/gnome/desktop/session/idle-delay', 'value': 0 }
    - { 'key': '/org/gnome/desktop/screensaver/lock-enabled', 'value': 'false' }
    - { 'key': '/org/gnome/desktop/screensaver/lock-delay', 'value': 0 }
  loop_control:
    loop_var: option
