---
- name: Set up package managers for required tools
  include_role:
    name: ccdc-package-manager-configuration

- name: Install desktop environment
  yum:
    name:
      - "@^gnome-desktop-environment"
      - firefox
      # This is required for the dconf module to disable screen locking
      - python2-psutil
      # DKMS will stop system updates from breaking VM guest extensions
      - dkms
  become: yes

- include_tasks: Linux.yml
