---
- name: Set up package managers for required tools
  include_role:
    name: ccdc-package-manager-configuration

- name: Install desktop environment
  package:
    name: "{{ package }}"
  loop: "{{ desktop_packages }}"
  loop_control:
    loop_var: package
  become: yes

- include_tasks: Linux.yml
