---
- name: Install autologon
  win_chocolatey:
    name: autologon
    state: present
    
- name: "Enable autologon for vagrant"
  win_command: "C:\\ProgramData\\chocolatey\\bin\\Autologon.exe vagrant . vagrant"
