---
- name: Install autologon
  chocolatey.chocolatey.win_chocolatey:
    name: autologon
    state: present
  become: true

- name: "Enable autologon for vagrant"
  ansible.windows.win_command: "C:\\ProgramData\\chocolatey\\bin\\Autologon.exe vagrant . {{ ansible_password }}"

- name: Disable screen saver
  ansible.windows.win_shell: Set-ItemProperty "HKCU:\Control Panel\Desktop" -Name ScreenSaveActive -Value 0 -Type DWord

- name: Disable monitor and standby idle timeout
  ansible.windows.win_command: powercfg -x -{{ timeout }} 0
  loop:
    - monitor-timeout-ac
    - monitor-timeout-dc
    - standby-timeout-ac
    - standby-timeout-dc
  loop_control:
    loop_var: timeout
